import type { Metadata } from 'next'
import { Public_Sans } from 'next/font/google'
import './globals.css'
import Header from './_components/Header'
import Footer from './_components/Footer'



const inter = Public_Sans({
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'E-commerce',
  description: 'Generated by Technomasr',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col gap-5 min-h-screen`}
        suppressHydrationWarning={true}
      >
        <Header />
        <main className='flex-grow mt-[15rem]'>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
